In [ ]:
import numpy as np
import pandas as pd

# Parameters
num_times = 100  # number of different times in the time series
num_points_per_time = 100  # number of points for each time
num_features = 3  # number of features
anomaly_ratio = 0.01  # ratio of anomalies per time

# Create an empty DataFrame
df = pd.DataFrame()

# Generate data
for t in range(num_times):
    # Create baseline time series for this time point
    baseline = np.random.randn(num_points_per_time, num_features)

    # Add periodic patterns
    for i in range(num_features):
        baseline[:, i] += np.sin(np.linspace(0, 10, num_points_per_time)) * (i + 1) * 0.5

    # Introduce anomalies
    num_anomalies = int(num_points_per_time * anomaly_ratio)
    anomaly_indices = np.random.choice(num_points_per_time, num_anomalies, replace=False)
    baseline[anomaly_indices] += np.random.randn(num_anomalies, num_features) * 3

    # Append to DataFrame
    temp_df = pd.DataFrame(baseline, columns=[f'Feature_{i+1}' for i in range(num_features)])
    temp_df['Time'] = t
    temp_df['Anomaly'] = 0
    temp_df.loc[anomaly_indices, 'Anomaly'] = 1
    df = pd.concat([df, temp_df], ignore_index=True)

# Shuffle the DataFrame
df = df.sample(frac=1).reset_index(drop=True)

# Display the first few rows of the DataFrame
df

In [ ]:
import numpy as np

def generate_synthetic_time_series(num_times, num_points_per_time):
    """
    Generate a synthetic time series dataset.

    :param num_times: Number of different times in the time series.
    :param num_points_per_time: Number of points for each time.
    :return: A list of lists of lists containing the synthetic time series data.
    """
    num_features = 3  # Number of features
    anomaly_ratio = 0.01  # Ratio of anomalies per time

    # Initialize an empty list for all times
    all_times_data = []

    # Generate data
    for t in range(num_times):
        # Create baseline time series for this time point
        baseline = np.random.randn(num_points_per_time, num_features)

        # Add periodic patterns
        for i in range(num_features):
            baseline[:, i] += np.sin(np.linspace(0, 10, num_points_per_time)) * (i + 1) * 0.5

        # Introduce anomalies
        num_anomalies = int(num_points_per_time * anomaly_ratio)
        anomaly_indices = np.random.choice(num_points_per_time, num_anomalies, replace=False)
        baseline[anomaly_indices] += np.random.randn(num_anomalies, num_features) * 3

        # Convert to list and append to the main list
        time_data = np.array(baseline.tolist())
        all_times_data.append(time_data)

    return all_times_data

# Example usage
data = generate_synthetic_time_series(100, 100)

# The 'data' variable is a list of lists of lists. Each sublist represents one time point,
# and within each sublist, each sub-sublist represents one data point with 3 features.
data

In [ ]:
def generate_synthetic_time_series(num_times, num_points_per_time, amplitude=1, noise_level=0.5):
    """
    Generate a synthetic time series dataset with enhanced periodic patterns.

    :param num_times: Number of different times in the time series.
    :param num_points_per_time: Number of points for each time.
    :param amplitude: Amplitude of the sine wave.
    :param noise_level: Standard deviation of the random noise.
    :return: A list of lists of lists containing the synthetic time series data.
    """
    num_features = 3  # Number of features
    anomaly_ratio = 0.01  # Ratio of anomalies per time

    all_times_data = []

    for t in range(num_times):
        baseline = np.zeros((num_points_per_time, num_features))

        for i in range(num_features):
            baseline[:, i] = amplitude * np.sin(np.linspace(0, 10, num_points_per_time) + np.pi / num_features * i)

        # Add noise
        baseline += np.random.randn(num_points_per_time, num_features) * noise_level

        # Introduce anomalies
        num_anomalies = int(num_points_per_time * anomaly_ratio)
        anomaly_indices = np.random.choice(num_points_per_time, num_anomalies, replace=False)
        baseline[anomaly_indices] += np.random.randn(num_anomalies, num_features) * 3

        all_times_data.append(np.array(baseline.tolist()))

    return all_times_data

data = generate_synthetic_time_series(100, 100)
data

In [ ]:
import numpy as np

def generate_scaled_sphere_point_cloud(num_points, scale_min, scale_max):
    """
    Generate a scaled 3D point cloud of a sphere shape.

    Parameters:
    num_points (int): The number of points to generate in the point cloud.
    scale_min (float): The minimum scale value for the points.
    scale_max (float): The maximum scale value for the points.

    Returns:
    np.array: A numpy array of shape (num_points, 3) representing the scaled 3D points.
    """

    # Generate spherical coordinates
    phi = np.random.uniform(0, np.pi, num_points)  # azimuthal angle
    theta = np.random.uniform(0, 2*np.pi, num_points)  # polar angle

    # Random scaling for each point
    scale = np.random.uniform(scale_min, scale_max, num_points)

    # Convert to Cartesian coordinates and apply scaling
    x = scale * np.sin(phi) * np.cos(theta)
    y = scale * np.sin(phi) * np.sin(theta)
    z = scale * np.cos(phi)

    return np.vstack((x, y, z)).T

def generate_animated_scaled_sphere_point_cloud(num_points, num_frames, scale_min_func, scale_max_func):
    """
    Generate a series of scaled 3D point clouds of a sphere shape, with scaling varying according to provided functions.

    Parameters:
    num_points (int): The number of points in each point cloud.
    num_frames (int): The number of different point clouds to generate.
    scale_min_func (function): A function to compute the minimum scale value for each frame.
    scale_max_func (function): A function to compute the maximum scale value for each frame.

    Returns:
    List[np.array]: A list of numpy arrays, each representing a scaled 3D point cloud.
    """

    point_clouds = []
    for frame in range(num_frames):
        scale_min = scale_min_func(frame, num_frames)
        scale_max = scale_max_func(frame, num_frames)

        # Generate scaled point cloud for the current frame
        scaled_points = generate_scaled_sphere_point_cloud(num_points, scale_min, scale_max)
        point_clouds.append(scaled_points)

    return point_clouds

# Define scaling functions based on a sinusoidal wave
def scale_min_func(frame, num_frames):
    return 0.5 * (np.sin(frame / num_frames * 2 * np.pi) + 1)  # oscillates between 0 and 1

def scale_max_func(frame, num_frames):
    return 1.5 + 0.5 * (np.sin(frame / num_frames * 2 * np.pi) + 1)  # oscillates between 1.5 and 2

# Example usage
num_points = 1000
num_frames = 100

# Generate the animated point clouds
animated_point_clouds = generate_animated_scaled_sphere_point_cloud(num_points, num_frames, scale_min_func, scale_max_func)

animated_point_clouds

In [ ]:
import numpy as np

###############################################################################################
# Generate a scaled 3D point cloud of a sphere shape filled with points with sinusoidal wave. #  -   START
###############################################################################################
def generate_scaled_sphere_point_cloud(num_points, scale_min, scale_max):
    """
    Generate a scaled 3D point cloud of a sphere shape.

    Parameters:
    num_points (int): The number of points to generate in the point cloud.
    scale_min (float): The minimum scale value for the points.
    scale_max (float): The maximum scale value for the points.

    Returns:
    np.array: A numpy array of shape (num_points, 3) representing the scaled 3D points.
    """

    # Generate spherical coordinates
    phi = np.random.uniform(0, np.pi, num_points)  # azimuthal angle
    theta = np.random.uniform(0, 2*np.pi, num_points)  # polar angle

    # Random scaling for each point
    scale = np.random.uniform(scale_min, scale_max, num_points)

    # Convert to Cartesian coordinates and apply scaling
    x = scale * np.sin(phi) * np.cos(theta)
    y = scale * np.sin(phi) * np.sin(theta)
    z = scale * np.cos(phi)

    return np.vstack((x, y, z)).T

def generate_animated_scaled_sphere_point_cloud(num_points, num_frames, scale_min_func, scale_max_func):
    """
    Generate a series of scaled 3D point clouds of a sphere shape, with scaling varying according to provided functions.

    Parameters:
    num_points (int): The number of points in each point cloud.
    num_frames (int): The number of different point clouds to generate.
    scale_min_func (function): A function to compute the minimum scale value for each frame.
    scale_max_func (function): A function to compute the maximum scale value for each frame.

    Returns:
    List[np.array]: A list of numpy arrays, each representing a scaled 3D point cloud.
    """

    point_clouds = []
    for frame in range(num_frames):
        scale_min = scale_min_func(frame)
        scale_max = scale_max_func(frame)

        # Generate scaled point cloud for the current frame
        scaled_points = generate_scaled_sphere_point_cloud(num_points, scale_min, scale_max)
        point_clouds.append(scaled_points)

    return point_clouds

def scale_min_func(frame, num_frames, num_cycles, scale_min, scale_max):
    """ Oscillates between 0 and 1 over a specified number of cycles. """
    return scale_min + (scale_max - scale_min) * 0.5 * (1 + np.sin(frame / num_frames * num_cycles * 2 * np.pi))

def scale_max_func(frame, num_frames, num_cycles, scale_min, scale_max):
    """ Oscillates between 1.5 and 2 over a specified number of cycles. """
    return scale_max + (scale_max - scale_min) * 0.5 * (1 + np.sin(frame / num_frames * num_cycles * 2 * np.pi))
###############################################################################################
# Generate a scaled 3D point cloud of a sphere shape filled with points with sinusoidal wave. #  -   END
###############################################################################################

num_points = 10             # Number of points to generate in each frame
num_frames = 20             # Number of frames to generate
scale_min = 0.1      # Minimum scale value for the points
scale_max = 1.0      # Maximum scale value for the points
num_cycles = 2         # Number of cycles for the oscillation


frames_data = generate_animated_scaled_sphere_point_cloud(
        num_points, 
        num_frames, 
        lambda frame: scale_min_func(frame, num_frames, num_cycles, scale_min, scale_max), 
        lambda frame: scale_max_func(frame, num_frames, num_cycles, scale_min, scale_max)
    )

frames_data

In [1]:
import numpy as np

def generate_base_sphere_point_cloud(num_points):
    # Generate spherical coordinates
    phi = np.random.uniform(0, np.pi, num_points)
    theta = np.random.uniform(0, 2*np.pi, num_points)

    # Convert to Cartesian coordinates
    x = np.sin(phi) * np.cos(theta)
    y = np.sin(phi) * np.sin(theta)
    z = np.cos(phi)

    return np.vstack((x, y, z)).T

def apply_sinusoidal_transformation(base_points, frame, num_frames, scale_min, scale_max, num_waves):
    # Compute scaling factor for this frame
    scale = scale_min + (scale_max - scale_min) * (np.sin(frame / num_frames * 2 * np.pi * num_waves) + 1) / 2

    # Apply scaling to each point
    transformed_points = base_points * scale

    return transformed_points

# Example usage
num_points = 1000
num_frames = 100
scale_min = 0.5
scale_max = 1.5
num_waves = 2

# Generate the base point cloud
base_point_cloud = generate_base_sphere_point_cloud(num_points)

# Generate the animated point clouds
animated_point_clouds = [
    apply_sinusoidal_transformation(base_point_cloud, frame, num_frames, scale_min, scale_max, num_waves) 
    for frame in range(num_frames)
]
animated_point_clouds

[array([[-0.00579377,  0.0896649 ,  0.99595514],
        [-0.18596068, -0.75407919, -0.62990729],
        [-0.17628042,  0.38687404,  0.90512634],
        ...,
        [ 0.16750298, -0.60684031,  0.77697335],
        [-0.63622891, -0.45319434,  0.62436181],
        [ 0.01735822,  0.19776254, -0.98009626]]),
 array([[-0.00615685,  0.09528389,  1.05836828],
        [-0.19761421, -0.80133478, -0.66938145],
        [-0.18732732,  0.41111813,  0.96184754],
        ...,
        [ 0.17799982, -0.64486894,  0.82566364],
        [-0.67609922, -0.48159449,  0.66348845],
        [ 0.018446  ,  0.21015565, -1.04151557]]),
 array([[-0.0065142 ,  0.10081427,  1.11979712],
        [-0.20908395, -0.84784513, -0.70823308],
        [-0.1982    ,  0.43497987,  1.01767422],
        ...,
        [ 0.18833112, -0.68229784,  0.87358606],
        [-0.71534076, -0.50954676,  0.70199804],
        [ 0.01951662,  0.22235331, -1.10196627]]),
 array([[-0.00686019,  0.10616882,  1.17927291],
        [-0.22018903, -0