In [ ]:
import numpy as np
import pandas as pd

# Parameters
num_times = 100  # number of different times in the time series
num_points_per_time = 100  # number of points for each time
num_features = 3  # number of features
anomaly_ratio = 0.01  # ratio of anomalies per time

# Create an empty DataFrame
df = pd.DataFrame()

# Generate data
for t in range(num_times):
    # Create baseline time series for this time point
    baseline = np.random.randn(num_points_per_time, num_features)

    # Add periodic patterns
    for i in range(num_features):
        baseline[:, i] += np.sin(np.linspace(0, 10, num_points_per_time)) * (i + 1) * 0.5

    # Introduce anomalies
    num_anomalies = int(num_points_per_time * anomaly_ratio)
    anomaly_indices = np.random.choice(num_points_per_time, num_anomalies, replace=False)
    baseline[anomaly_indices] += np.random.randn(num_anomalies, num_features) * 3

    # Append to DataFrame
    temp_df = pd.DataFrame(baseline, columns=[f'Feature_{i+1}' for i in range(num_features)])
    temp_df['Time'] = t
    temp_df['Anomaly'] = 0
    temp_df.loc[anomaly_indices, 'Anomaly'] = 1
    df = pd.concat([df, temp_df], ignore_index=True)

# Shuffle the DataFrame
df = df.sample(frac=1).reset_index(drop=True)

# Display the first few rows of the DataFrame
df

In [ ]:
import numpy as np

def generate_synthetic_time_series(num_times, num_points_per_time):
    """
    Generate a synthetic time series dataset.

    :param num_times: Number of different times in the time series.
    :param num_points_per_time: Number of points for each time.
    :return: A list of lists of lists containing the synthetic time series data.
    """
    num_features = 3  # Number of features
    anomaly_ratio = 0.01  # Ratio of anomalies per time

    # Initialize an empty list for all times
    all_times_data = []

    # Generate data
    for t in range(num_times):
        # Create baseline time series for this time point
        baseline = np.random.randn(num_points_per_time, num_features)

        # Add periodic patterns
        for i in range(num_features):
            baseline[:, i] += np.sin(np.linspace(0, 10, num_points_per_time)) * (i + 1) * 0.5

        # Introduce anomalies
        num_anomalies = int(num_points_per_time * anomaly_ratio)
        anomaly_indices = np.random.choice(num_points_per_time, num_anomalies, replace=False)
        baseline[anomaly_indices] += np.random.randn(num_anomalies, num_features) * 3

        # Convert to list and append to the main list
        time_data = np.array(baseline.tolist())
        all_times_data.append(time_data)

    return all_times_data

# Example usage
data = generate_synthetic_time_series(100, 100)

# The 'data' variable is a list of lists of lists. Each sublist represents one time point,
# and within each sublist, each sub-sublist represents one data point with 3 features.
data

In [ ]:
def generate_synthetic_time_series(num_times, num_points_per_time, amplitude=1, noise_level=0.5):
    """
    Generate a synthetic time series dataset with enhanced periodic patterns.

    :param num_times: Number of different times in the time series.
    :param num_points_per_time: Number of points for each time.
    :param amplitude: Amplitude of the sine wave.
    :param noise_level: Standard deviation of the random noise.
    :return: A list of lists of lists containing the synthetic time series data.
    """
    num_features = 3  # Number of features
    anomaly_ratio = 0.01  # Ratio of anomalies per time

    all_times_data = []

    for t in range(num_times):
        baseline = np.zeros((num_points_per_time, num_features))

        for i in range(num_features):
            baseline[:, i] = amplitude * np.sin(np.linspace(0, 10, num_points_per_time) + np.pi / num_features * i)

        # Add noise
        baseline += np.random.randn(num_points_per_time, num_features) * noise_level

        # Introduce anomalies
        num_anomalies = int(num_points_per_time * anomaly_ratio)
        anomaly_indices = np.random.choice(num_points_per_time, num_anomalies, replace=False)
        baseline[anomaly_indices] += np.random.randn(num_anomalies, num_features) * 3

        all_times_data.append(np.array(baseline.tolist()))

    return all_times_data

data = generate_synthetic_time_series(100, 100)
data

In [1]:
import numpy as np

def generate_scaled_sphere_point_cloud(num_points, scale_min, scale_max):
    """
    Generate a scaled 3D point cloud of a sphere shape.

    Parameters:
    num_points (int): The number of points to generate in the point cloud.
    scale_min (float): The minimum scale value for the points.
    scale_max (float): The maximum scale value for the points.

    Returns:
    np.array: A numpy array of shape (num_points, 3) representing the scaled 3D points.
    """

    # Generate spherical coordinates
    phi = np.random.uniform(0, np.pi, num_points)  # azimuthal angle
    theta = np.random.uniform(0, 2*np.pi, num_points)  # polar angle

    # Random scaling for each point
    scale = np.random.uniform(scale_min, scale_max, num_points)

    # Convert to Cartesian coordinates and apply scaling
    x = scale * np.sin(phi) * np.cos(theta)
    y = scale * np.sin(phi) * np.sin(theta)
    z = scale * np.cos(phi)

    return np.vstack((x, y, z)).T

def generate_animated_scaled_sphere_point_cloud(num_points, num_frames, scale_min_func, scale_max_func):
    """
    Generate a series of scaled 3D point clouds of a sphere shape, with scaling varying according to provided functions.

    Parameters:
    num_points (int): The number of points in each point cloud.
    num_frames (int): The number of different point clouds to generate.
    scale_min_func (function): A function to compute the minimum scale value for each frame.
    scale_max_func (function): A function to compute the maximum scale value for each frame.

    Returns:
    List[np.array]: A list of numpy arrays, each representing a scaled 3D point cloud.
    """

    point_clouds = []
    for frame in range(num_frames):
        scale_min = scale_min_func(frame, num_frames)
        scale_max = scale_max_func(frame, num_frames)

        # Generate scaled point cloud for the current frame
        scaled_points = generate_scaled_sphere_point_cloud(num_points, scale_min, scale_max)
        point_clouds.append(scaled_points)

    return point_clouds

# Define scaling functions based on a sinusoidal wave
def scale_min_func(frame, num_frames):
    return 0.5 * (np.sin(frame / num_frames * 2 * np.pi) + 1)  # oscillates between 0 and 1

def scale_max_func(frame, num_frames):
    return 1.5 + 0.5 * (np.sin(frame / num_frames * 2 * np.pi) + 1)  # oscillates between 1.5 and 2

# Example usage
num_points = 1000
num_frames = 100

# Generate the animated point clouds
animated_point_clouds = generate_animated_scaled_sphere_point_cloud(num_points, num_frames, scale_min_func, scale_max_func)

animated_point_clouds

[array([[-0.82377952, -0.0810246 ,  0.1717686 ],
        [-0.38101696,  0.2637301 ,  1.92048932],
        [ 0.99929182, -0.55109597, -0.31993179],
        ...,
        [ 0.12139234, -0.3621557 ,  0.77051926],
        [-1.27652081, -0.18305022, -0.84506399],
        [-0.48541388, -0.15906305, -1.71969088]]),
 array([[ 0.56131181,  0.62154468, -1.02756366],
        [ 0.99174354, -0.04248864, -1.20199714],
        [-0.6310939 ,  0.19359484, -1.27689988],
        ...,
        [-0.28252025, -0.56893282,  1.10376052],
        [ 0.37171606, -0.57103085, -0.0754954 ],
        [ 1.31001287,  1.2917674 ,  0.39973987]]),
 array([[ 0.64090224,  0.38279655,  0.54492691],
        [ 0.00791252,  0.01396734, -1.0121691 ],
        [ 0.31574048,  0.11917359, -0.90226815],
        ...,
        [-0.40134116, -1.84364953, -0.46435541],
        [-0.74073835,  1.17880821, -0.41377304],
        [-0.64351418, -0.02107974,  1.07193333]]),
 array([[ 0.31444134, -0.17868595,  1.67898431],
        [-0.07717114,  0